question_data = [
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Chris Jericho's Catchphrase is: Best in the World!",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Sheamus And Cesaro are also known as The Bar",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Rey Mysterio is a 3-Time World Champion",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Jhon Cena is a 17 time world champion",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Randy Ortan won the Royal Rumble 2017",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Stone Cold Steve Austin has 3 Rumble wins",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Randy Ortan is a 14 time world champion",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Brock Lesner is the member of The New Day",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Brock Lesner was the cover page of the 2k17 game edition",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: WWE",
            "type": "boolean",
            "difficulty": "easy",
            "question": "MiZ is not a grand slam champion",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    
]
